<html>
  <head>
    <title>ูฺฏูุง ุณุช</title>
    <meta name="description" content="ุงู ุณุงุช ููููู ุจููุงู ุฏุฑุจุงุฑู ุฑูุณุชุง ุขุจุฏ ุงุณุช">
  </head>
  <body>
    <h1>ุณูุงู! ูู ุจููุงู ูุณุชู ๐</h1>
    <p>ุงู ุงููู ุณุงุช ููู ๐</p>

    <h2>ุฏุฑุจุงุฑู ุฑูุณุชุง ุขุจุฏ</h2>
    <p>ุขุจุฏ ฺฉ ุฑูุณุชุง ุฒุจุง ุฏุฑ ุฎูุฒุณุชุงู ุงุณุช. ุงู ุฑูุณุชุง ุงุฒ ุทุงููโูุง ฺฏูุฌุนูโููุฏุ ูู ู ุฎุงูุจุงุจุง ุชุดฺฉู ุดุฏู ู ูู ุจููุงู ุงุฒ ุทุงูู ฺฏูุฌุนูโููุฏ ูุณุชู ู ุจูโุนููุงู ุฎุงู ุฏุฑ ุงู ุฑูุณุชุง ุดูุงุฎุชู ูโุดูู.</p>
    <p>ุฑูุณุชุง ุขุจุฏ ุจู ุฎุงุทุฑ ุชูุงุดโูุง ูู ุฏุฑ ุตูุญ ู ุขุฑุงูุดุ ููุด ููู ุฏุฑ ููุทูู ุฏุงุฑุฏ ู ูุฑุดุฏ ุฏุณุช ุฑุงุณุช ูู ู ููฺฉุฑ ููุงุฏุงุฑู ุนููุจ ูุฒ ุฏุฑ ฺฉูุงุฑ ูู ูุณุชูุฏ.</p>
  </body>
</html>
